language: ruby

cache: bundler

rvm:
  - 2.3.5
  - 2.4.2

matrix:
  fast_finish: true

services: mongodb

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

script:
  - bundle exec rake
